version: '3'
services:
  flask-app:
    build:
      context: ./flask_server 
      dockerfile: Dockerfile  
    ports:
      - "5000:5000" 
    volumes:
      - ./flask_server:/server 

  react-app:
    build:
      context: ./webui  
      dockerfile: Dockerfile.webui  
    ports:
      - "3000:3000" 

